services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: db_admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kepler_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: