"""keywords table

Revision ID: 016bf858b6e4
Revises: 43b1a98b2786
Create Date: 2024-04-24 11:31:26.453796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '016bf858b6e4'
down_revision = '43b1a98b2786'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('reference_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    with op.batch_alter_table('keywords', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_keywords_id'), ['id'], unique=False)

    op.create_table('products_categories_association',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_category_id'], ['product_categories.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'product_category_id')
    )
    op.create_table('products_keywords_association',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'keyword_id')
    )
    op.drop_table('product_categories_association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_categories_association',
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_category_id'], ['product_categories.id'], name='product_categories_association_product_category_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_categories_association_product_id_fkey')
    )
    op.drop_table('products_keywords_association')
    op.drop_table('products_categories_association')
    with op.batch_alter_table('keywords', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_keywords_id'))

    op.drop_table('keywords')
    # ### end Alembic commands ###
