"""order total price

Revision ID: 4182a37db16b
Revises: db28cd02637a
Create Date: 2024-06-10 22:11:28.226433

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4182a37db16b'
down_revision = 'db28cd02637a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buyers_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('total_currency', sa.String(length=3), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('buyers_orders', schema=None) as batch_op:
        batch_op.drop_column('total_currency')
        batch_op.drop_column('total_price')

    # ### end Alembic commands ###
