"""products locked stock

Revision ID: 50d9a9739e0f
Revises: 73d82b5392e3
Create Date: 2024-05-19 22:09:46.479544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50d9a9739e0f'
down_revision = '73d82b5392e3'
branch_labels = None
depends_on = None

# TODO update trigger @DiegoCaspi


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_locked_stock', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('current_locked_stock')

    # ### end Alembic commands ###
