"""shipments init

Revision ID: 58b09be75b2d
Revises: 4182a37db16b
Create Date: 2024-06-15 11:00:01.577985

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '58b09be75b2d'
down_revision = '4182a37db16b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('current_status', sa.Enum('ACCEPTED', 'SHIPPED', 'IN_DELIVERY', 'DELIVERED', name='shipmentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid')
    )
    with op.batch_alter_table('sellers_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipment_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'shipments', ['shipment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sellers_orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('shipment_id')

    op.drop_table('shipments')
    # ### end Alembic commands ###
