"""reviews seller product removed

Revision ID: c9ce5d5552a5
Revises: ecdc452f26c7
Create Date: 2024-06-21 18:18:35.633585

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c9ce5d5552a5'
down_revision = 'ecdc452f26c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_reviews', schema=None) as batch_op:
        batch_op.drop_index('ix_product_reviews_seller_order_id')
        batch_op.drop_constraint('product_reviews_seller_order_id_fkey', type_='foreignkey')
        batch_op.drop_column('seller_order_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('product_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_order_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('product_reviews_seller_order_id_fkey', 'sellers_orders', ['seller_order_id'], ['id'])
        batch_op.create_index('ix_product_reviews_seller_order_id', ['seller_order_id'], unique=False)

    # ### end Alembic commands ###
